#ifndef header_h
#define header_h

String fileIndex=
"<html lang=\"it\">"
"  <head>"
"   <meta charset=\"UTF-8\">"
"   <title>Casa</title>"
"     <link rel=\"icon\" href=\"http://www.comune.uragodoglio.bs.it/sites/www.comune.uragodoglio.bs.it/files/2-Hot-Home-icon.png\">"
"   <script src=\"https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js\"></script>"
"   <link href=\"https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css\" rel=\"stylesheet\" type=\"text/css\">"
"   <script type=\"text/javascript\" src=\"index.js\"></script>"
"   <link href=\"style.css\" rel=\"stylesheet\" type=\"text/css\">"
" </head>"
" <body>"
"   <h1 class=\"titolo\">Benvenuto nella tua casa</h1>"
"   <div id=\"alert\" style=\"display:none\">"
"     <strong id=\"titAlert\"></strong><span id=\"textAlert\"></span><button class=\"close\" onClick=\"closeAlert()\">x</button>"
"   </div>"
"   <div class=\"col-sm-4\">"
"     <div class=\"panel panel-info\">"
"       <div class=\"panel-heading\">"
"         <h3 class=\"panel-title\">Comando</h3>"
"       </div>"
"       <div class=\"panel-body\">"
"         <input type=\"text\" id=\"comando\" class=\"form-control input-lg campo\">"
"         <button class=\"btn btn-lg btn-primary btnInvia\" onClick=\"inviaComando()\">Invia</button>"
"       </div>"
"     </div>"
"     <div class=\"panel panel-info\">"
"       <div class=\"panel-heading\">"
"         <h3 class=\"panel-title\">Telecomando</h3>"
"       </div>"
"       <div class=\"panel-body\">"
"         <div class=\"col-sm-6\">"
"           <div class=\"row\">"
"             <button class=\" btn btn-lg btn-danger glyphicon glyphicon-off \" id=\"pow\" onClick=\"tvCommand('pow')\"></button>"
"             <button class=\" btn btn-lg glyphicon glyphicon-volume-off \" onClick=\"tvCommand('noVol')\"></button>"
"             <button class=\" btn btn-lg glyphicon glyphicon glyphicon-menu-hamburger\" onClick=\"tvCommand('menu')\"></button>"
"           </div>"
"           <div class=\"row\">"
"             <button class=\"btn btn-lg btnTel\" onClick=\"tvCommand('1')\">1</button>"
"             <button class=\"btn btn-lg btnTel\" onClick=\"tvCommand('2')\">2</button>"
"             <button class=\"btn btn-lg btnTel\" onClick=\"tvCommand('3')\">3</button>"
"           </div>"
"           <div class=\"row\">"
"             <button class=\"btn btn-lg btnTel\" onClick=\"tvCommand('4')\">4</button>"
"             <button class=\"btn btn-lg btnTel\" onClick=\"tvCommand('5')\">5</button>"
"             <button class=\"btn btn-lg btnTel\" onClick=\"tvCommand('6')\">6</button>"
"           </div>"
"           <div class=\"row\">"
"             <button class=\"btn btn-lg btnTel\" onClick=\"tvCommand('7')\">7</button>"
"             <button class=\"btn btn-lg btnTel\" onClick=\"tvCommand('8')\">8</button>"
"             <button class=\"btn btn-lg btnTel\" onClick=\"tvCommand('9')\">9</button>"
"           </div>"
"           <div class=\"row\">"
"             <button class=\"btn btn-lg btnTel\">0</button>"
"             <button class=\"btn btn-lg btnTel\" onClick=\"tvCommand('info')\">INFO</button>"
"           </div>"
"         </div>"
"         <div class=\"col-sm-6\">"
"           <div class=\"row\">"
"             <button class=\"btn btn-lg btnTel\" onClick=\"tvCommand('vol+')\">Vol +</button>"
"             <button class=\"btn btn-lg btnTel\" onClick=\"tvCommand('p+')\">P +</button>"
"           </div>"
"           <div class=\"row\">"
"             <button class=\"btn btn-lg btnTel\" onClick=\"tvCommand('vol-')\">Vol -</button>"
"             <button class=\"btn btn-lg btnTel\" onClick=\"tvCommand('p-')\">P -</button>"
"           </div>"
"           <div class=\"row\">"
"             <button class=\"btn btn-lg btnTel\" onClick=\"tvCommand('source')\">SOURCE</button>"
"           </div>"
"           <div class=\"row\">"
"             <button class=\"btn btn-lg btnTel\" onClick=\"tvCommand('exit')\">EXIT</button>"
"             <button class=\"btn btn-lg glyphicon glyphicon-menu-up btnTel\" onClick=\"tvCommand('su')\"></button>"
"           </div>"
"           <div class=\"row\">"
"             <button class=\"btn btn-lg glyphicon glyphicon-menu-left btnTel\" onClick=\"tvCommand('sx')\"></button>"
"             <button class=\"btn btn-lg btnTel\" onClick=\"tvCommand('p-')\">OK</button>"
"             <button class=\"btn btn-lg glyphicon glyphicon-menu-right btnTel\" onClick=\"tvCommand('dx')\"></button>"
"           </div>"
"           <div class=\"row\">"
"             <button class=\"btn btn-lg btnTel\" onClick=\"tvCommand('back')\">BACK</button>"
"             <button class=\"btn btn-lg glyphicon glyphicon-menu-down btnTel\" onClick=\"tvCommand('giu')\"></button>"
"           </div>"
"         </div>"
"       </div>"
"     </div>"
"   </div>"
"   <div class=\"col-sm-8\">"
"     <div class=\"panel panel-info\">"
"       <div class=\"panel-heading\">"
"         <h3 class=\"panel-title\">Lo stato di casa</h3>"
"       </div>"
"       <div class=\"panel-body\">"
"         <div class=\"col-sm-4\">"
"           <h3>Orario: <label class=\"clock\">22:15</label></h3>"
"           <h3>Data: 14/07/2016</h3>"
"           <h3>Temperatura: <label class=\"label label-warning\">20°C</label></h3>"
"           <h3>Umidità: <label class=\"label label-primary\">30%</label></h3>"
"           <h3>Pir: <label id=\"pi\" class=\"label label-success\">ON</label></h3>"
"           <h3>Luce: <label id=\"luc\" class=\"label label-danger\">OFF</label></h3>"
"         </div>"
"         <div class=\"col-sm-8\">"
"           <h3>Max Temp: <label class=\"label label-danger\">30°C</label> Ora: <label class=\"clock\">13:37</label></h3>"
"           <h3>Min Temp: <label class=\"label label-info\">15°C</label> Ora: <label class=\"clock\">4:19</label></h3>"
"           <h3>Max Hum:  <label class=\"label label-danger\">70%</label> Ora: <label class=\"clock\">14:03</label></h3>"
"           <h3>Min Hum:  <label class=\"label label-primary\">30%</label> Ora: <label class=\"clock\">4:00</label></h3>"
"           <h3>Ultimo rilevamento pir: 14/07/2016 <label class=\"clock\">22:15</label></h3>"
"         </div>"
"       </div>"
"     </div>"
"     <div class=\"panel panel-info\">"
"       <div class=\"panel-heading\">"
"         <h3 class=\"panel-title\">Comando</h3>"
"       </div>"
"       <div class=\"panel-body\">"
"         <button class=\"btn btn-lg btn-primary glyphicon glyphicon-repeat\" onClick=\"aggiorna()\"></button>"
"         <button class=\"btn btn-lg btn-success\" id=\"luce\" onClick=\"changeLuce()\">LUCE ON</button>"
"         <button class=\"btn btn-lg btn-danger\" id=\"pir\" onClick=\"changePir()\">PIR OFF</button>"
"       </div>"
"     </div>"
"   </div>"
" </body>"
"</html>";

String fileCss= 
".titolo{"
" text-align: center;"
"}"
".campo{"
" width: 70%;"
" float: left;"
"}"
".btnInvia{"
" float: right;"
"}"
".btnTel{"
" margin: 1%;"
"}"
".myAlert{"
" margin-left: auto;"
" margin-right:auto;"
" width: 70%;"
"}"
".clock{"
" font-family: digital-clock-font;"
"}";

String fileJs=
"function inviaComando()"
"{"
" var comando = $(\"#comando\").val();"
" if(comando == undefined || comando == \"\")"
"   printAlert(\"err\",\"Devi inserire un comando\");"
" else"
" {"
"   var s = comando.split(\" \");"
"   if(s[1] == undefined || s[1] == \"\")"
"     printAlert(\"err\",\"Devi inserire un valore per il comando\");"
"   else"
"     ajaxComando(s[0],s[1]);"
" }"
"}"
"function changeLuce()"
"{"
" if ($(\"#luce\").attr(\"class\") == \"btn btn-lg btn-success\")"
"   ajaxComando(\"luce\", \"on\");"
" else"
"   ajaxComando(\"luce\", \"off\");"
"}"
"function changePir()"
"{"
" if ($(\"#pir\").attr(\"class\") == \"btn btn-lg btn-success\")"
"   ajaxComando(\"pir\", \"on\");"
" else"
"   ajaxComando(\"pir\", \"off\");"
"}"
"function tvCommand(txt)"
"{"
" if(txt==\"pow\")"
" {"
"   if($(\"#pow\").attr(\"class\") == \"btn btn-lg btn-success glyphicon glyphicon-off\")"
"      txt=\"on\";"
"   else "
      "txt=\"off\";"
" }"
" ajaxComando(\"tv\", txt);"
"}"
"function aggiorna()"
"{"
" ajaxComando(\"refresh\",\"all\");"
"}"
"function printAlert(type, val)"
"{"
" $(\"#alert\").show();"
" if(type==\"ok\")"
" {"
"   $(\"#alert\").attr(\"class\",\"alert alert-success fade in alert-dismissable myAlert\");"
"   $(\"#titAlert\").text(\"Tutto bene: \");"
"   $(\"#textAlert\").text(val);"
" }"
" else"
" {"
"   $(\"#alert\").attr(\"class\",\"alert alert-danger fade in alert-dismissable myAlert\");"
"   $(\"#titAlert\").text(\"Errore: \");"
"   $(\"#textAlert\").text(val);"
" }"
"}"
"function closeAlert()"
"{"
" $(\"#alert\").hide();"
"}"
"function ajaxComando(tipo, val)"
"{"
"  $.get({"
"    url: \"/comando\","
"    data: {\"comando\" : tipo, \"val\" : val},"
"    success: function (data){"
"      var obj=JSON.parse(data);"
"      printAlert(obj.header,obj.payload);"
"      if(obj.header==\"ok\")"
"      {"
          "switch(tipo)"
  "       {"
    "        case \"luce\":"
    "          if(val==\"on\"){"
    "             $(\"#luc\").attr(\"class\",\"label label-success\");"
    "             $(\"#luc\").text(\"ON\");"
              "   $(\"#luce\").attr(\"class\",\"btn btn-lg btn-danger\");"
              "   $(\"#luce\").text(\"LUCE OFF\");"
    "          }"
    "          else{"
              "   $(\"#luce\").attr(\"class\",\"btn btn-lg btn-success\");"
              "   $(\"#luce\").text(\"LUCE ON\");"
    "             $(\"#luc\").attr(\"class\",\"label label-danger\");"
    "             $(\"#luc\").text(\"OFF\");"
    "         }"
    "        break;"
    "        case \"pir\":"
    "          if(val==\"on\"){"
    "             $(\"#pi\").attr(\"class\",\"label label-success\");"
    "             $(\"#pi\").text(\"ON\");"
              "   $(\"#pir\").attr(\"class\",\"btn btn-lg btn-danger\");"
              "   $(\"#pir\").text(\"PIR OFF\");"
    "          }"
    "          else{"
    "             $(\"#pi\").attr(\"class\",\"label label-danger\");"
    "             $(\"#pi\").text(\"OFF\");"
              "   $(\"#pir\").attr(\"class\",\"btn btn-lg btn-success\");"
              "   $(\"#pir\").text(\"PIR ON\");"
    "          }"
    "        break;"
    "        case \"tv\":"
        "      if(val==\"on\")"
                " $(\"#pow\").attr(\"class\",\"btn btn-lg btn-danger glyphicon glyphicon-off\");"
               "if(val==\"off\")"
                 "$(\"#pow\").attr(\"class\",\"btn btn-lg btn-success glyphicon glyphicon-off\");"
    "        break;"
    "        case \"refresh\":"
                  "var data = new Date();"  
                  "alert(\"Nuova presenza:\"+data.getDate()+\"-\"+(data.getMonth()+1)+\"-\"+data.getFullYear()+\" \"+data.getHours()+\":\"+data.getMinutes());"
    "        break;"
    "     }"
    "  }"
    "}"
"  });"
"}";
#endif
